# Generated by Django 5.1.5 on 2026-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_officer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='station',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
