# Generated by Django 5.1.5 on 2026-05-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bankstaff_rename_username_officer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nirastaff',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='nirastaff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nirastaff',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='nirastaff',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='nirastaff',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='nirastaff',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='nirastaff',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
