# Generated by Django 5.1.5 on 2026-05-10 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_unebstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='unebstaff',
            name='exam_role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
