# Generated by Django 5.1.5 on 2026-05-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auditlog_idrecord_flag_reason_idrecord_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrecord',
            name='id_number',
            field=models.CharField(max_length=100),
        ),
    ]
