# Generated by Django 5.1.5 on 2026-05-12 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_atmreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmreport',
            name='card_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Frozen', 'Frozen')], default='Frozen', max_length=20),
        ),
        migrations.AddField(
            model_name='atmreport',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
