# Generated by Django 5.1.5 on 2026-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_atmreport_card_status_atmreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedid',
            name='report_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='idrecord',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
