# Generated by Django 5.1.5 on 2026-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_flaggedid_report_count_idrecord_report_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrecord',
            name='id_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
