# Generated by Django 5.1.5 on 2026-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_idrecord_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='idrecord',
            name='officer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
