# Generated by Django 5.1.5 on 2026-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_idrecord_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location_found', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Closed', 'Closed')], default='Lost', max_length=20)),
                ('officer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('report_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
