# Generated by Django 5.1.5 on 2026-05-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_driverpermit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('severity', models.CharField(default='low', max_length=50)),
                ('status', models.CharField(default='Under Review', max_length=50)),
                ('report_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostPermitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UDLSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UDLSStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('reviewer', 'Reviewer')], default='officer', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnebStaff',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='location_found',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='phone',
        ),
        migrations.AddField(
            model_name='driverpermit',
            name='class_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='driverpermit',
            name='holder_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='driverpermit',
            name='location_reported',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverpermit',
            name='national_id',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='driverpermit',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='flag_reason',
            field=models.CharField(blank=True, default='UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='permit_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('processing', 'Processing'), ('rejected', 'Rejected')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='flaggedpermit',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driverpermit'),
        ),
    ]
