# Generated by Django 5.1.5 on 2026-06-02 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_flaggedpermit_lostpermitreport_udlsactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idrecord',
            name='id_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid NIN format. Example: CM12345678ABC', regex='^C[FM][A-Za-z0-9]{12}$')]),
        ),
    ]
