# Generated by Django 5.1.5 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_idrecord_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverpermit',
            old_name='permit_number',
            new_name='license_number',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='driverpermit',
            name='national_id',
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='location_reported',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='reported_by',
            field=models.CharField(default='UDLS Staff', max_length=255),
        ),
        migrations.AlterField(
            model_name='driverpermit',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Lost', max_length=20),
        ),
    ]
